import { CampusLocation } from '../types/game';

export const CAMPUS_LOCATIONS: CampusLocation[] = [
  {
    id: 'xim_main_gate',
    key: 'xim_main_gate',
    name: 'XIM Main Gate & Admin Plaza',
    shortName: '1. Main Gate',
    requiredLevel: 1,
    description: 'The grand main entrance welcoming XIM University scholars.',
    lore: 'Where every student journey begins with ambition, energy, and high spirits.',
    statBonus: '+1 Base Focus',
    coordinates: { x: 14, y: 82 },
    icon: 'DoorOpen',
    color: '#10b981'
  },
  {
    id: 'xim_old_academic',
    key: 'xim_old_academic',
    name: 'Old Academic Building',
    shortName: '2. Old Academic',
    requiredLevel: 2,
    description: 'Original heritage academic block with classic classroom halls.',
    lore: 'Generations of business and tech alumni learned their core fundamentals here.',
    statBonus: '+2 Intellect boost',
    coordinates: { x: 48, y: 58 },
    icon: 'GraduationCap',
    color: '#6366f1'
  },
  {
    id: 'xim_new_academic',
    key: 'xim_new_academic',
    name: 'New Academic Building',
    shortName: '3. New Academic',
    requiredLevel: 3,
    description: 'State-of-the-art smart lecture halls with digital presentation setups.',
    lore: 'Interactive case studies, presentations, and workshops take place here.',
    statBonus: '+10% XP on Intellect quests',
    coordinates: { x: 58, y: 50 },
    icon: 'GraduationCap',
    color: '#06b6d4'
  },
  {
    id: 'xim_ic_building',
    key: 'xim_ic_building',
    name: 'IC Building (Innovation & Tech)',
    shortName: '4. IC Building',
    requiredLevel: 4,
    description: 'Information & Computing building hosting computer labs and incubation.',
    lore: 'Coding hackathons, data analytics, and cloud computing projects.',
    statBonus: '+15% Coin reward on quests',
    coordinates: { x: 66, y: 44 },
    icon: 'Cpu',
    color: '#14b8a6'
  },
  {
    id: 'xim_auditorium',
    key: 'xim_auditorium',
    name: 'Main Auditorium',
    shortName: '5. Main Auditorium',
    requiredLevel: 5,
    description: 'Grand 1000+ seat auditorium hosting cultural fests & keynotes.',
    lore: 'Music nights, drama performances, and corporate leadership convocations.',
    statBonus: '+20% Coin reward',
    coordinates: { x: 76, y: 28 },
    icon: 'Award',
    color: '#f43f5e'
  },
  {
    id: 'xim_pg_hostel',
    key: 'xim_pg_hostel',
    name: 'PG Residence & Executive Quarters',
    shortName: '6. PG Residence',
    requiredLevel: 6,
    description: 'Quiet residential quarters for postgraduate and executive scholars.',
    lore: 'Focused environment for advanced research, internships, and placement prep.',
    statBonus: '+1 Base Intellect',
    coordinates: { x: 42, y: 36 },
    icon: 'Building',
    color: '#a855f7'
  },
  {
    id: 'xim_girls_hostel',
    key: 'xim_girls_hostel',
    name: "Girls' Hostel Block",
    shortName: "7. Girls' Hostel",
    requiredLevel: 7,
    description: 'Modern residential residence quarters for female scholars.',
    lore: 'High-energy residence filled with teamwork, study sessions, and laughter.',
    statBonus: '+1 Base Focus',
    coordinates: { x: 30, y: 44 },
    icon: 'Building',
    color: '#ec4899'
  },
  {
    id: 'xim_boys_hostel',
    key: 'xim_boys_hostel',
    name: "Boys' Hostel Block",
    shortName: "8. Boys' Hostel",
    requiredLevel: 8,
    description: 'Residential halls for male scholars equipped with common rooms.',
    lore: 'Late-night gaming tournaments, group study, and hostel camaraderie.',
    statBonus: '+1 Base Strength',
    coordinates: { x: 20, y: 52 },
    icon: 'Building',
    color: '#3b82f6'
  },
  {
    id: 'xim_volley',
    key: 'xim_volley',
    name: 'Volleyball Court',
    shortName: '9. Volley Court',
    requiredLevel: 9,
    description: 'Sand & hard-court volleyball arena near the athletic zone.',
    lore: 'Spike matches and team practice sessions build stamina and coordination.',
    statBonus: '+1 Strength & +1 Focus',
    coordinates: { x: 22, y: 62 },
    icon: 'Dumbbell',
    color: '#eab308'
  },
  {
    id: 'xim_basketball',
    key: 'xim_basketball',
    name: 'Basketball Court',
    shortName: '10. Basketball Court',
    requiredLevel: 10,
    description: 'Floodlit outdoor court for high-octane 3v3 basketball matches.',
    lore: 'Fast-paced matches after evening classes draw cheering crowds.',
    statBonus: '+2 Strength boost',
    coordinates: { x: 16, y: 66 },
    icon: 'Dumbbell',
    color: '#f97316'
  },
  {
    id: 'xim_cricket',
    key: 'xim_cricket',
    name: 'Cricket Ground & Sports Pitch',
    shortName: '11. Cricket Ground',
    requiredLevel: 11,
    description: 'Expansive green cricket turf hosting inter-departmental tournaments.',
    lore: 'Weekend cricket leagues, boundaries, and sports fest championships.',
    statBonus: '+2 Base Strength',
    coordinates: { x: 86, y: 48 },
    icon: 'Award',
    color: '#10b981'
  },
  {
    id: 'xim_vendors',
    key: 'xim_vendors',
    name: 'Vendors Side & Food Stalls',
    shortName: '12. Vendors Side',
    requiredLevel: 12,
    description: 'Bustling food corner with tea stalls, quick bites, and street snacks.',
    lore: 'Late night conversations over hot chai and samosas fuel student bonding.',
    statBonus: '+1 Focus boost',
    coordinates: { x: 30, y: 70 },
    icon: 'Coffee',
    color: '#f97316'
  },
  {
    id: 'xim_cafeteria',
    key: 'xim_cafeteria',
    name: 'Central Cafeteria',
    shortName: '13. Cafeteria',
    requiredLevel: 13,
    description: 'Main campus dining hall serving daily meals and refreshing drinks.',
    lore: 'Energy hub where morning plans and group project discussions happen.',
    statBonus: '+1 Strength boost',
    coordinates: { x: 38, y: 58 },
    icon: 'Coffee',
    color: '#eab308'
  },
  {
    id: 'xim_dispensary',
    key: 'xim_dispensary',
    name: 'Campus Dispensary & Health Center',
    shortName: '14. Dispensary',
    requiredLevel: 14,
    description: 'Medical care facility providing 24/7 health assistance for students.',
    lore: 'Quick recovery for weary scholars after long study nights.',
    statBonus: '+5% HP Recovery',
    coordinates: { x: 22, y: 78 },
    icon: 'HeartPulse',
    color: '#ef4444'
  },
  {
    id: 'xim_library',
    key: 'xim_library',
    name: 'XIM Central Library & Commons',
    shortName: '15. XIM Library',
    requiredLevel: 15,
    description: 'Multi-floor digital library stocked with thousands of journals & research databases.',
    lore: 'Quiet sanctuary where top GPA scholars spend midnight study sessions.',
    statBonus: '+15% XP on all quests',
    coordinates: { x: 54, y: 30 },
    icon: 'BookOpen',
    color: '#8b5cf6'
  },
  {
    id: 'xim_faculty_residence',
    key: 'xim_faculty_residence',
    name: 'Faculty Residence & Convocation Lawn',
    shortName: '16. Faculty Residence',
    requiredLevel: 16,
    description: 'Serene faculty quarters and convocation gardens.',
    lore: 'The ultimate pinnacle of academic excellence at XIM University.',
    statBonus: 'XIM Legend Status (+25% XP & Coins)',
    coordinates: { x: 90, y: 16 },
    icon: 'Shield',
    color: '#fbbf24'
  }
];

